### ISSUE TITLE
RSS includes posts about Jurassic World Evolution

### ISSUE THREAD

**Issue by kokarn** [Athanasius/ed-devtracker#11]
Heya!

First, Merry Christmas!

Secondly, I've noticed the devs have started posting about other things, especially Brett C about Jurassic World Evolution.
Are you doing some sort of subforum checking? If not, that might be needed now.
Thanks for providing a great service!

**Comment by Athanasius** [comment]
From https://ed.miggy.org/devposts.html

"Caveat 1 - The feeds will only contain the fully public posts from the forums, i.e. nothing from the Private Backers Forum or the Alpha Backers Forum. **Also you'll see all Frontier Developments forum posts, not just those relating to Elite: Dangerous.**"

I don't want to have to scramble to ensure I don't *miss* posts every time they decide to re-arrange the forums and add new ones.  I'd suggest looking into what filtering you can do in your RSS reader of choice (I use Tiny Tiny RSS where it would be trivial to add such).

**Comment by kokarn** [comment]
Hmm, yeah that's a possibility. It would require me to blacklist some phrases tho which isn't ideal but might be the best solution.

I'm guessing you have no interest in adding what section each post is into a custom XML namespace in the RSS for easier filtering?

**Comment by Athanasius** [comment]
The " (text)" at the end of each item's title is the name of the forum it's in.  For this use case that will always be " (Jurassic World Evolution)", as it's the sub-forum the post is in.  The full bread-crumbs for that one were "Forum > Games by Frontier Developments > 2011 - 2019 > Jurassic World Evolution".  That text in the item title will only ever show the deepest sub-forum for the post.

I'd have to look into how easy it is to add custom namespaces given the library I'm using to generate the RSS XML.  I think I looked at this once before for something else and it was going to be convoluted and fragile.

**Comment by Athanasius** [comment]
I should note that this "deepest sub-forum name" actually comes from the forum Acivity List I use to get the posts in the first place.  For this one go to https://forums.frontier.co.uk/member.php/52-Brett-C and then click "BrettC's Activity" and then the "Brett C" sub-tab under that.

I'll have a think about whether blacklisting some sub-forums isn't going to be too fragile.

**Comment by kokarn** [comment]
I totally overlooked the sub forum in the title, that's great. 

That's something I can easily use because I already have integrated support for that in the dev tracker.

If you feel you want to also do black-listing that's cool but I totally understand that might be way out of scope.
